### ISSUE TITLE
The branch in vosk interference docker installation doesn't exist 

### ISSUE THREAD

**Issue by peace20162** [vistec-AI/commonvoice-th#1]
I try to install the vosk-interference but it say that the lookahead-1.8.0 branch doesn't exist. Is there are any branches that can substitute the component?

**Comment by zairosoft** [comment]
RUN cd /opt \
    && git clone -b vosk --single-branch https://github.com/alphacep/kaldi /opt/kaldi \
    && cd /opt/kaldi/tools \

**Comment by peace20162** [comment]
thank you

**Comment by zairosoft** [comment]
@peace20162 can you test model after training finished ?
so i don't know local file after training finished

**Comment by peace20162** [comment]
@nakhonsoft  normally it's in exp folder. the model has .mdl .

**Comment by nakhonsoft** [comment]
@peace20162 you mean this folder
Folder: commonvoice-th/vosk-inference/model/am/final.mdl

**Comment by zairosoft** [comment]
@peace20162 my exp folder

https://www.dropbox.com/s/pmvvb40q64a2gma/Screenshot%20%281%29.png?dl=0

**Comment by zairosoft** [comment]
@peace20162 Did you mean to find the .mdl file in the exp folder?

**Comment by peace20162** [comment]
@nakhonsoft  yes

**Comment by peace20162** [comment]
@nakhonsoft  if you wanna try the model on the website. you can follow https://github.com/ekapolc/ASR_classproject/tree/master/hookup.

**Comment by zairosoft** [comment]
@peace20162 commonvoice-th dataset Model is less accurate
I'm making a dataset from youtube
https://github.com/EgorLakomkin/KTSpeechCrawler

**Comment by zairosoft** [comment]
@peace20162 now test on android app Model is less accurate
project offline on robot
